"""Create Table

Revision ID: 0001
Revises: 
Create Date: 2024-01-01 23:11:23.745647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_champion_id'), 'champion', ['id'], unique=False)
    op.create_table('league',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_id'), 'league', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('summonerName', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('teamId', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Enum('top', 'jungle', 'mid', 'bot', 'support', name='position_type'), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_table('tournament',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('leagueId', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('startDate', sa.Date(), nullable=False),
    sa.Column('endDate', sa.Date(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['leagueId'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournament_id'), 'tournament', ['id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tournamentId', sa.BigInteger(), nullable=False),
    sa.Column('startTime', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('unStarted', 'finished', 'inProgress', name='state_enum'), nullable=False),
    sa.Column('team1Id', sa.BigInteger(), nullable=False),
    sa.Column('team2Id', sa.BigInteger(), nullable=False),
    sa.Column('team1Score', sa.SmallInteger(), nullable=False),
    sa.Column('team2Score', sa.SmallInteger(), nullable=False),
    sa.Column('winnerId', sa.BigInteger(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['team1Id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2Id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['tournamentId'], ['tournament.id'], ),
    sa.ForeignKeyConstraint(['winnerId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('matchId', sa.BigInteger(), nullable=False),
    sa.Column('team1Id', sa.BigInteger(), nullable=False),
    sa.Column('team2Id', sa.BigInteger(), nullable=False),
    sa.Column('gameNumber', sa.SmallInteger(), nullable=False),
    sa.Column('winnerId', sa.BigInteger(), nullable=True),
    sa.Column('gameTime', sa.Time(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['matchId'], ['match.id'], ),
    sa.ForeignKeyConstraint(['team1Id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team2Id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['winnerId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_table('playerstats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('playerId', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Enum('top', 'jungle', 'mid', 'bot', 'support', name='position_type'), nullable=False),
    sa.Column('champion', sa.Integer(), nullable=True),
    sa.Column('kills', sa.SmallInteger(), nullable=False),
    sa.Column('deaths', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('golds', sa.Integer(), nullable=True),
    sa.Column('cs', sa.SmallInteger(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('damageDealt', sa.Integer(), nullable=True),
    sa.Column('damageTaken', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['champion'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['gameId'], ['game.id'], ),
    sa.ForeignKeyConstraint(['playerId'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playerstats_id'), 'playerstats', ['id'], unique=False)
    op.create_table('teamstats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gameId', sa.BigInteger(), nullable=False),
    sa.Column('teamId', sa.BigInteger(), nullable=False),
    sa.Column('ban1', sa.Integer(), nullable=True),
    sa.Column('ban2', sa.Integer(), nullable=True),
    sa.Column('ban3', sa.Integer(), nullable=True),
    sa.Column('ban4', sa.Integer(), nullable=True),
    sa.Column('ban5', sa.Integer(), nullable=True),
    sa.Column('pick1', sa.Integer(), nullable=False),
    sa.Column('pick2', sa.Integer(), nullable=False),
    sa.Column('pick3', sa.Integer(), nullable=False),
    sa.Column('pick4', sa.Integer(), nullable=False),
    sa.Column('pick5', sa.Integer(), nullable=False),
    sa.Column('kills', sa.SmallInteger(), nullable=False),
    sa.Column('deaths', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('golds', sa.Integer(), nullable=False),
    sa.Column('towers', sa.SmallInteger(), nullable=False),
    sa.Column('heralds', sa.SmallInteger(), nullable=True),
    sa.Column('drakes', sa.ARRAY(sa.Enum('normal', 'chemtech', 'cloud', 'hextech', 'infernal', 'mountain', 'ocean', 'elder', name='drake_type')), nullable=True),
    sa.Column('barons', sa.SmallInteger(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ban1'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['ban2'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['ban3'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['ban4'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['ban5'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['gameId'], ['game.id'], ),
    sa.ForeignKeyConstraint(['pick1'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['pick2'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['pick3'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['pick4'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['pick5'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teamstats_id'), 'teamstats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teamstats_id'), table_name='teamstats')
    op.drop_table('teamstats')
    op.drop_index(op.f('ix_playerstats_id'), table_name='playerstats')
    op.drop_table('playerstats')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_tournament_id'), table_name='tournament')
    op.drop_table('tournament')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_league_id'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_champion_id'), table_name='champion')
    op.drop_table('champion')
    # ### end Alembic commands ###
