"""Update Champion table

Revision ID: 0002
Revises: 0001
Create Date: 2024-02-04 23:43:11.292676

"""
from typing import Sequence, Union
from sqlalchemy.sql import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("DROP TABLE if exists champion cascade"))
    op.create_table('champion',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_champion_key'), 'champion', ['key'], unique=True)

    op.create_foreign_key(None, 'playerstats', 'champion', ['champion'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['pick3'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['ban4'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['ban1'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['ban5'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['ban3'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['pick4'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['pick5'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['pick2'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['pick1'], ['key'])
    op.create_foreign_key(None, 'teamstats', 'champion', ['ban2'], ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.get_bind().execute(text("DROP TABLE if exists champion cascade"))
    op.create_table('champion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_champion_id'), 'champion', ['id'], unique=True)

    op.create_foreign_key('teamstats_ban3_fkey', 'teamstats', 'champion', ['ban3'], ['id'])
    op.create_foreign_key('teamstats_ban2_fkey', 'teamstats', 'champion', ['ban2'], ['id'])
    op.create_foreign_key('teamstats_pick4_fkey', 'teamstats', 'champion', ['pick4'], ['id'])
    op.create_foreign_key('teamstats_pick3_fkey', 'teamstats', 'champion', ['pick3'], ['id'])
    op.create_foreign_key('teamstats_ban4_fkey', 'teamstats', 'champion', ['ban4'], ['id'])
    op.create_foreign_key('teamstats_ban1_fkey', 'teamstats', 'champion', ['ban1'], ['id'])
    op.create_foreign_key('teamstats_pick2_fkey', 'teamstats', 'champion', ['pick2'], ['id'])
    op.create_foreign_key('teamstats_pick1_fkey', 'teamstats', 'champion', ['pick1'], ['id'])
    op.create_foreign_key('teamstats_pick5_fkey', 'teamstats', 'champion', ['pick5'], ['id'])
    op.create_foreign_key('teamstats_ban5_fkey', 'teamstats', 'champion', ['ban5'], ['id'])
    op.create_foreign_key('playerstats_champion_fkey', 'playerstats', 'champion', ['champion'], ['id'])
    # ### end Alembic commands ###
