"""Update Player table schema

Revision ID: 0003
Revises: 0002
Create Date: 2024-02-11 13:52:52.521858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_champion_key', table_name='champion')
    op.create_index(op.f('ix_champion_key'), 'champion', ['key'], unique=False)
    op.alter_column('player', 'position',
               existing_type=postgresql.ENUM('top', 'jungle', 'mid', 'bot', 'support', name='position_type'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'position',
               existing_type=postgresql.ENUM('top', 'jungle', 'mid', 'bot', 'support', name='position_type'),
               nullable=False)
    op.drop_index(op.f('ix_champion_key'), table_name='champion')
    op.create_index('ix_champion_key', 'champion', ['key'], unique=True)
    # ### end Alembic commands ###
